[package]
name = "sync-service"
version = "0.0.1"
edition = "2021"
authors = ["DGRV Digital Tools Team <dev@dgrv.io>"]
license = "MIT"

[dependencies]
common = { path = "../common" }
tokio = { workspace = true }
serde = { workspace = true }
sqlx = { workspace = true }
uuid = { workspace = true }